[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11",
    #"scikit-build>=0.16.7",
    #"cmake>=3.18",
    #"nanobind>=1.1.0",
    #"ninja; platform_system!='Windows'"
]

build-backend = "setuptools.build_meta"